RENAME TABLE `#__imageshow_theme_classic` TO `#__imageshow_theme_classic_flash`;

CREATE TABLE IF NOT EXISTS `#__imageshow_theme_classic_javascript` (
  `theme_id` int(11) unsigned NOT NULL auto_increment,
  `imgpanel_presentation_mode` char(30) default '0',
  `imgpanel_img_click_action_fit` char(30) default '',
  `imgpanel_img_open_link_in_fit` char(30) default 'new-browser',
  `imgpanel_img_click_action_expand` char(30) default '',
  `imgpanel_img_open_link_in_expand` char(30) default 'new-browser',
  `imgpanel_bg_type` char(30) default '',
  `imgpanel_bg_value` char(255) default NULL,
  `thumbpanel_show_panel` char(30) default NULL,
  `thumbpanel_panel_position` char(30) default '',
  `thumbpanel_active_state_color` char(30) default NULL,
  `thumbpanel_thumnail_normal_state` char(30) default NULL,
  `thumbpanel_border` char(30) default NULL,
  `thumbpanel_thumb_width` char(30) default NULL,
  `thumbpanel_thumb_height` char(30) default NULL,
  `thumbpanel_thumnail_panel_color` char(30) default NULL,
  `infopanel_panel_position` char(30) default '',
  `infopanel_presentation` char(30) default NULL,
  `infopanel_bg_color_fill` char(30) default NULL,
  `infopanel_panel_click_action` char(30) default NULL,
  `infopanel_open_link_in` char(30) default 'new-browser',
  `infopanel_show_title` char(30) default 'yes',
  `infopanel_title_css` char(250) default NULL,
  `infopanel_show_des` char(30) default 'yes',
  `infopanel_des_lenght_limitation` char(30) default '',
  `infopanel_des_css` char(250) default NULL,
  `infopanel_show_link` char(30) default 'no',
  `infopanel_link_css` char(250) default NULL,
  `toolbarpanel_presentation` char(30) default '0',
  `toolbarpanel_show_counter` char(30) default 'no',
  `slideshow_slide_timing` char(50) default NULL,
  `slideshow_auto_play` char(30) default 'no',
  `slideshow_looping` char(30) default 'yes',
  `general_round_corner_radius` char(30) DEFAULT '',
  `general_border_color` char(30) DEFAULT '',
  `general_background_color` char(30) DEFAULT '',
  `general_border_stroke` char(30) DEFAULT '',
  PRIMARY KEY  (`theme_id`)
) DEFAULT CHARSET=utf8;